### ISSUE TITLE
Bug with press Configuration and start game

### ISSUE THREAD

**Issue by KiwisOBS34** [Mirsario/TerrariaOverhaul#149]
When I press Configuration and when start game, Terraria is shutdown
![6786869](https://user-images.githubusercontent.com/103123372/184786262-838f7355-f856-4c29-bd9d-66cfdd9cffa5.PNG)

**Comment by KiwisOBS34** [comment]
Log file:
[22:14:03.824] [Main Thread/DEBUG] [tML]: Process.Start (UseShellExecute = True): "C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json"
[22:14:04.156] [Main Thread/WARN] [tML]: Silently Caught Exception:
System.ComponentModel.Win32Exception: An error occurred trying to start process 'C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json' with working directory 'D:\Steam\steamapps\common\tModLoader'. Указанному файлу не сопоставлено ни одно приложение для выполнения данной операции.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at Terraria.ModLoader.Engine.LoggingHooks.<>c.b__1_0(Func`2 orig, Process self) in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 21
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at TerrariaOverhaul.Common.MainMenuOverlays.ConfigurationMenuButton.OnClicked() in TerrariaOverhaul\Common\MainMenuOverlays\ConfigurationMenuButton.cs:line 12
at TerrariaOverhaul.Common.MainMenuOverlays.MenuLine.Update(Vector2 position) in TerrariaOverhaul\Common\MainMenuOverlays\MenuLine.cs:line 43
at TerrariaOverhaul.Common.MainMenuOverlays.MainMenuOverlaySystem.DrawOverlay(SpriteBatch sb) in TerrariaOverhaul\Common\MainMenuOverlays\MainMenuOverlaySystem.cs:line 85
at DMDTerraria.Main::DrawMenu(Main this, GameTime gameTime)
at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49044
at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48619
at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs) in tModLoader\Terraria\Program.cs:line 192
at MonoLaunch.<>c__DisplayClass1_0.

b__0() in tModLoader\Terraria\MonoLaunch.cs:line 56
at System.Threading.Thread.StartCallback()
[22:14:04.157] [Main Thread/ERROR] [Terraria]: System.ComponentModel.Win32Exception (1155): An error occurred trying to start process 'C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json' with working directory 'D:\Steam\steamapps\common\tModLoader'. Указанному файлу не сопоставлено ни одно приложение для выполнения данной операции.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at Terraria.ModLoader.Engine.LoggingHooks.<>c.b__1_0(Func`2 orig, Process self) in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 21
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at TerrariaOverhaul.Common.MainMenuOverlays.ConfigurationMenuButton.OnClicked() in TerrariaOverhaul\Common\MainMenuOverlays\ConfigurationMenuButton.cs:line 12
at TerrariaOverhaul.Common.MainMenuOverlays.MenuLine.Update(Vector2 position) in TerrariaOverhaul\Common\MainMenuOverlays\MenuLine.cs:line 43
at TerrariaOverhaul.Common.MainMenuOverlays.MainMenuOverlaySystem.DrawOverlay(SpriteBatch sb) in TerrariaOverhaul\Common\MainMenuOverlays\MainMenuOverlaySystem.cs:line 85
at DMDTerraria.Main::DrawMenu(Main this, GameTime gameTime)
at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49044
at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48630
[22:14:04.176] [Main Thread/FATAL] [tML]: Main engine crash

System.ComponentModel.Win32Exception (1155): An error occurred trying to start process 'C:/Users/User\Documents\My Games\Terraria\tModLoader-preview\TerrariaOverhaul\Config.json' with working directory 'D:\Steam\steamapps\common\tModLoader'. Указанному файлу не сопоставлено ни одно приложение для выполнения данной операции.
at System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
at Terraria.ModLoader.Engine.LoggingHooks.<>c.b__1_0(Func`2 orig, Process self) in tModLoader\Terraria\ModLoader\Engine\LoggingHooks.cs:line 21
at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
at TerrariaOverhaul.Common.MainMenuOverlays.ConfigurationMenuButton.OnClicked() in TerrariaOverhaul\Common\MainMenuOverlays\ConfigurationMenuButton.cs:line 12
at TerrariaOverhaul.Common.MainMenuOverlays.MenuLine.Update(Vector2 position) in TerrariaOverhaul\Common\MainMenuOverlays\MenuLine.cs:line 43
at TerrariaOverhaul.Common.MainMenuOverlays.MainMenuOverlaySystem.DrawOverlay(SpriteBatch sb) in TerrariaOverhaul\Common\MainMenuOverlays\MainMenuOverlaySystem.cs:line 85
at DMDTerraria.Main::DrawMenu(Main this, GameTime gameTime)
at Terraria.Main.DoDraw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 49044
at Terraria.Main.Draw(GameTime gameTime) in tModLoader\Terraria\Main.cs:line 48630
at Microsoft.Xna.Framework.Game.Tick() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 562
at Microsoft.Xna.Framework.Game.RunLoop() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 878
at Microsoft.Xna.Framework.Game.Run() in D:\a\tModLoader\tModLoader\FNA\src\Game.cs:line 419
at Terraria.Program.LaunchGame_(Boolean isServer) in tModLoader\Terraria\Program.cs:line 231
[22:14:04.181] [Main Thread/DEBUG] [TerrariaSteamClient]: Send: shutdown
