### ISSUE TITLE
"Reported from in-game: not compatible with zooming" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#26]
tModLoader version: 0.11.6.2
 
| Mods:  | - | - |
| :--- | :--- | :--- |
| `AutoReforge 1.3.7` | `Cactus Damage - Config Update (that works) 1.6` | `Calamity Mod (No Calamity Music) 1.4.3.1` |
| `Calamity Mod Music 1.4.3.1` | `Cheat Extensions for Hero's/Cheat Sheet 0.1.1` | `Cheat Sheet 0.6.4` |
| `Calamity Mod Extra Music 1.0.7.5` | `Crit Sound Effects 1.2.3` | `Customizable Defense 1.0.1` |
| `Health and Mana From Bosses 1.1.2.1` | `Faster Tools 1.4` | `Yet Another Boss Health Bar 1.3.2` |
| `Flight Left Timer 1.3.4` | `Fresh Start 1.0.2` | `GoodProLib - Beta 0.2` |
| `Mod Helpers 5.4.3` | `+100% increased quality of life 0.8` | `Lan's Simple Healthbar 0.2.2` |
| `More Lunar Weapons 0.3.2.2` | `Paladin Armor 1.2` | `Plentiful Ores 2.0.1` |
| `Simple Sliders; Adjust HP, damage ecl\. 1.0` | `Sounder Mod 0.6.4.1` | `Star Mod 4.1` |
| `Starvation 2.2.1` | `Terraria Overhaul 4.3.2.1` | `Upgrade Equipment 1.0.3` |
| `WorldGen Previewer 0.3.1` | - | - |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| theancientsheep2 | True | False | 0 | 400 of 400 | 220 of 220 (200) | 36 |
 
**Player theancientsheep2's (0) equipment:**
 
| Head | Body | Legs | Accessory 1 | Accessory 2 | Accessory 3 | Accessory 4 | Accessory 5 | Vanity 1 | Vanity 2 | Vanity 3 | Vanity 4 |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| Palladium Mask | Palladium Breastplate | Palladium Leggings | Blue Horseshoe Balloon | Arcane Obsidian Shield | Tiger Climbing Gear | Anechoic Plating | Jagged Spectre Boots | Shadow Helmet | Shadow Scalemail | Shadow Greaves | Hard Titan Glove |
 
Is day: False, Time of day/night: 17388, Elapsed half days: 21
 
World name: fart2, world size: Small
 
World progress: Wall of Flesh killed
 
Items on ground: 371, Npcs active: 10
 
Player count: 1 (single-player)
 
Autopause: False
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 1
 
Is screen maximized: False
 
Screen resolution: 1426 802
 
Quality style: 2
 
Background on: True
 
Child safety: True
 
Game zoom: 1
 
UI zoom: 1.345865
 
FrameworkVersion.Framework: NetFramework
 
FrameworkVersion.Version: 4.7.2
 
 
 
Recent error logs:
```
...
at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
at System.Windows.Forms.Application.Run(Form mainForm)
at Microsoft.Xna.Framework.WindowsGameHost.Run()
at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
at Terraria.Program.LaunchGame_()
at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
at Terraria.WindowsLaunch.Main(String[] args)

[11:31:25] [29/INFO] [StatusText]: Saving world data
[11:31:25] [29/INFO] [StatusText]: Validating world save
[11:31:26] [29/INFO] [TerrariaOverhaul]: [OverhaulWorld] Saved season TerrariaOverhaul.Common.Systems.Gameplay.Seasons.Types.Winter
```
 
when you change the zooming on the screen thunder does not lay in the ground and trees are also effected by this

**Comment by Mirsario** [comment]
@hamstar0 dear god, fix your util and start hastebin'ing full log files.

**Comment by hamstar0** [comment]
I'd like to, but it will take some time before I can get around to it.

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
As it's a rebuild, and of higher quality at that, 99.9% issues from 1.3 do not apply to it.
