### ISSUE TITLE
"In-game: Grapple Crash" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#3]
Mods: ExperienceAndClasses 1.3.11, Mod Helpers 1.6.6.3, Mod of Redemption 0.4.8.9, Terraria Overhaul 2.1.9.1, Thorium Mod 1.5.0.3
 
Is day: True, Time of day/night: 29169, Elapsed half days: 57
 
World name: Expert Kilroy, world size: Large
 
World progress: Eye of Cthulhu killed, Eater of Worlds killed
 
Items on ground: 73, Npcs active: 21
 
Player info: Name: `Sam`, Male: True, Demon Heart: False, Difficulty mode: 0, Life: 251 of 251 (240) (200), Mana: 227 of 227, Defense: 29
 
Player equips: Head: Molten Helmet, Body: Molten Breastplate, Legs: Molten Greaves, Accessory: Guarding Drift Boots, Accessory: Turbo Boots, Accessory: Arcane Tungsten Bulwark, Accessory: Metal Detector, Accessory: Class Token: Hybrid (Tier II), Vanity: Warding Shield of Cthulhu, Vanity: Lucky Band of Regeneration, Vanity: Hard Lifeform Analyzer
 
Player count: 2 (multiplayer)
 
 
 
Recent error logs:
```
...
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.ThreadPoolTaskScheduler.TryExecuteTaskInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.TaskScheduler.TryRunInline(Task task, Boolean taskWasPreviouslyQueued)
   at System.Threading.Tasks.Task.InternalRunSynchronously(TaskScheduler scheduler, Boolean waitForCompletion)
   at Terraria.Netplay.OnUpdate()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

```
 
Using web grapple then switching to new grapple using it then jumping causes a crash

**Comment by Mirsario** [comment]
Closing all `1.3 (Legacy)` issues. TML is fully on 1.4 by now, and 5.0 of Overhaul is super worth switching to even if it's incomplete.
