### ISSUE TITLE
"In-game: Repair table crashes my game..." - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#4]
Mods: AlchemistNPC 7.4.1, Boss Checklist 0.1.5.5, Calamity Mod 1.3.4.1, Nathan's Tweaks 1.1.2, Yet Another Boss Health Bar 1.3.2, Mod Helpers 2.1.0.2, imkSushi's Mod 4.3.1, JoostMod 0.7.2.8, Luiafk 1.0.0.128, Magic Storage 0.4.3.3, Recipe Browser 0.7, Terraria Overhaul 2.1.9.1, VeinMiner 1.3.0.5
 
Is day: False, Time of day/night: 9566, Elapsed half days: 17
 
World name: PurifyTheWorld, world size: Large
 
World progress: Eye of Cthulhu killed, King Slime killed, Queen Bee killed, Brain of Cthulhu killed, Skeletron killed, Wall of Flesh killed, Destroyer killed, Twins killed, Skeletron Prime killed, Plantera killed, Golem killed
 
Items on ground: 3, Npcs active: 46
 
Player info: Name: `TheGoldenOne`, Male: True, Demon Heart: True, Difficulty mode: 0, Life: 570 of 570 (500) (200), Mana: 250 of 250, Defense: 110
 
Player equips: Head: Beetle Helmet, Body: Beetle Shell, Legs: Beetle Leggings, Accessory: Warding Bloody Worm Scarf, Accessory: Warding Void of Extinction, Accessory: Warding Angel Treads, Accessory: Warding Asgard's Valor, Accessory: Warding Starlight Wings, Accessory: Warding Deific Amulet, Vanity: Ancient Necro Helmet, Vanity: Gnunderson's Shiny Stone
 
Player count: 1 (single-player)
 
 
 
Recent error logs:
```
   at System.Array.Sort[T](T[] array, Int32 index, Int32 length, IComparer`1 comparer)
   at System.Collections.Generic.List`1.Sort(Comparison`1 comparison)
   at Terraria.GameContent.UI.Elements.UIList.UpdateOrder()
   at Terraria.GameContent.UI.Elements.UIList.AddRange(IEnumerable`1 items)
   at HamstarHelpers.Internals.ControlPanel.UIControlPanel.UpdateModList(ModHelpersMod mymod)
   at HamstarHelpers.ModHelpersWorld.PreUpdate()
   at Terraria.ModLoader.WorldHooks.PreUpdate()
   at Terraria.WorldGen.UpdateWorld()
   at Terraria.Main.DoUpdate(GameTime gameTime)
   at Terraria.Main.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
   at Microsoft.Xna.Framework.GameHost.OnIdle()
   at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
   at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
   at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at Microsoft.Xna.Framework.WindowsGameHost.Run()
   at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
   at Terraria.Program.LaunchGame(String[] args, Boolean monoArgs)
   at Terraria.WindowsLaunch.Main(String[] args)

```
 
when I put some tools are weapons in the repair table, it crashes my game, so I have to exit and reenter Terraria, this happened with my Picksaw. Hope y'all can find a fix for this bug.

**Comment by Mirsario** [comment]
Been fixed in 4.3, forgot to close this.
