### ISSUE TITLE
"Reported from in-game: small bug" - submitted via. helper utility

### ISSUE THREAD

**Issue by hamstar0** [Mirsario/TerrariaOverhaul#9]
| Mods:  | - | - |
| :--- | :--- | :--- |
| `AlchemistNPC 8.4` | `Auto Trash 0.4` | `Better Night Sky 1.1` |
| `Boss Highlights 1.0.0` | `Boss Checklist 0.2.1` | `Calamity Mod (No Calamity Music) 1.4.2.4` |
| `Capitalism 1.4.2.3` | `Calamity Mod Extra Music 1.0.6` | `JereTheJuggler's Custom Generation 1.1` |
| `More Dialogue 0.2` | `Various Weathers 1.0.0.6` | `Fargo's Mutant Mod 1.3` |
| `Fargo's Soul Mod 0.6.1` | `Glowing Water 1.0` | `Mod Helpers 4.4.0.1` |
| `Helpful NPCs 0.1.4` | `\[c/9bffb9\:Lighting Essentials\] 1.0` | `Luiafk 1.0.0.130` |
| `Magic Storage 0.4.3.3` | `MoreAccesories+ 2.3` | `Psycho\! 1.5.4` |
| `Recipe Browser 0.7.3` | `Reforge Armor 1.0` | `Spirit Mod 1.3.4.1` |
| `Stamina 2.0.7.1` | `SuperQuickRespawn 1.0.1` | `Terraria Overhaul 3.2.2` |
| `Utility Bombs Reborn 0.2.3.3` | `VeinMiner 1.3.0.5` | `Where's My Items 0.5.1` |
| `Wildlife Mod 0.12.0` | `Wing Slot 1.6.2` | `Which Mod Is This From? (WMITF) 2.6` |
 
| Name | Male | Has Demon Heart | Difficulty mode | Life | Mana | Defense |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| delphi | True | False | 0 | 92 of 100 | 40 of 40 | 0 |
 
**Player delphi's (0) equipment:**
 
| - |
| :--- |
| - |
 
Is day: True, Time of day/night: 33005, Elapsed half days: 1
 
World name: phobos, world size: Large
 
World progress: none
 
Items on ground: 2, Npcs active: 6
 
Player count: 1 (single-player)
 
Autopause: True
 
Autosave: True
 
Lighting mode: 0
 
Lighting threads: 0
 
Frame skip mode: 2
 
Is screen maximized: False
 
Screen resolution: 1366 768
 
Quality style: 0
 
Background on: True
 
Child safety: False
 
Game zoom: 1
 
UI zoom: 1
 
 
 
Recent error logs:
```
System.Reflection.TargetInvocationException occured in TerrariaOverhaul
Message:
Exception has been thrown by the target of an invocation.
Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at TerrariaOverhaul.OverhaulMod.PostSetupContent()
System.Reflection.TargetInvocationException occured in TerrariaOverhaul
Message:
Exception has been thrown by the target of an invocation.
Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at TerrariaOverhaul.OverhaulMod.PostSetupContent()
System.Reflection.TargetInvocationException occured in TerrariaOverhaul
Message:
Exception has been thrown by the target of an invocation.
Stacktrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at TerrariaOverhaul.OverhaulMod.PostSetupContent()
Initialized translations with 287 lines.
```
 
when i cut down the tree the animation is not working it just like the vanilla one

**Comment by Mirsario** [comment]
Been fixed in ~4.0.
